### ISSUE TITLE
Problem with criterias 

### ISSUE THREAD

**Issue by joe69** [tamershahin/grails-redis-flexible-cache#3]
Hello , 

my problem is , the plugin can not handle withCriteria or createCriteria created data. 

When i make 

def cache = redisFlexibleCacheService.doCache('gc_' + params.long('roundId') , 'gameCenter', 8, true, {
  def randomValue = 10 + Math.random() * 5
  Round selectedRoundValue = Round.get(params.long('roundId'))
  def competition = selectedRoundValue.competition

  def test = Round.withCriteria {
	eq("competition", competition)
	eq("season", Season.currentSeason)
	order 'roundNr', 'asc'
  }
  
  return [random:randomValue, selectedRound: selectedRoundValue, test:test]
} )

log.info("CACHE" + cache)

By the first time the its shows ok: 
GameCenterController CACHE[random:14.03080833953291, selectedRound:Regionalliga Mitte - #30 (Fr, 29.05.2015 19:00), test:[Regionalliga Mitte - #1 (Fr, 01.08.2014 18:30), Regionalliga Mitte - #2 (Fr, 08.08.2014 18:00), Regionalliga Mitte - #3  ....... ]

But after a refresh:
simple.MemoryPageFragmentCachingFilter Throwable thrown during doFilter on request with URI: /liga25/grails/gameCenter.dispatch and Query: null : Request processing failed; nested exception is org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at C__Users_Thomas_Projekte_Ligaportal_backend_liga25_grails_app_views_gameCenter_index_gsp$_run_closure2.doCall(index.gsp:172)
	at C__Users_Thomas_Projekte_Ligaportal_backend_liga25_grails_app_views_gameCenter_index_gsp.run(index.gsp:200)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at com.odobo.grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:106)
	at com.odobo.grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:74)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at at.ligaportal.ApiAuthenticationFilter.doFilter(ApiAuthenticationFilter.groovy:103)
	at com.odobo.grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:122)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	... 17 more
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	... 17 more
Caused by: org.gametube.redisflexiblecache.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for RedisFlexibleDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at org.gametube.redisflexiblecache.RedisFlexibleSerializer.deserialize(RedisFlexibleSerializer.java:40)
	at org.gametube.redisflexiblecache.RedisFlexibleCacheService.doCache(RedisFlexibleCacheService.groovy:121)
	at at.ligaportal.GameCenterController$_closure1$$EPFul1QN.doCall(GameCenterController.groovy:167)
	... 17 more
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for RedisFlexibleDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at org.gametube.redisflexiblecache.RedisFlexibleSerializer.deserialize(RedisFlexibleSerializer.java:38)
	... 19 more
Caused by: org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer.deserialize(RedisFlexibleDeserializer.java:49)
	... 20 more
Caused by: java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName(Class.java:274)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:625)
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer$1.resolveClass(RedisFlexibleDeserializer.java:40)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readClass(ObjectInputStream.java:1483)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1333)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.ArrayList.readObject(ArrayList.java:771)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1180)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer.deserialize(RedisFlexibleDeserializer.java:46)
	... 20 more
[/liga25].[grails] Servlet.service() for servlet grails threw exception
java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName(Class.java:274)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:625)
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer$1.resolveClass(RedisFlexibleDeserializer.java:40)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readClass(ObjectInputStream.java:1483)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1333)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.ArrayList.readObject(ArrayList.java:771)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1180)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer.deserialize(RedisFlexibleDeserializer.java:46)
	at org.gametube.redisflexiblecache.RedisFlexibleSerializer.deserialize(RedisFlexibleSerializer.java:38)
	at org.gametube.redisflexiblecache.RedisFlexibleCacheService.doCache(RedisFlexibleCacheService.groovy:121)
	at at.ligaportal.GameCenterController$_closure1$$EPFul1QN.doCall(GameCenterController.groovy:167)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at C__Users_Thomas_Projekte_Ligaportal_backend_liga25_grails_app_views_gameCenter_index_gsp$_run_closure2.doCall(index.gsp:172)
	at C__Users_Thomas_Projekte_Ligaportal_backend_liga25_grails_app_views_gameCenter_index_gsp.run(index.gsp:200)
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at com.odobo.grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:106)
	at com.odobo.grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:74)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at at.ligaportal.ApiAuthenticationFilter.doFilter(ApiAuthenticationFilter.groovy:103)
	at com.odobo.grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:122)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
errors.GrailsExceptionResolver ClassNotFoundException occurred when processing request: [GET] /liga25/
at.ligaportal.Round_$$_javassist_103. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:include>: Unable to execute include: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	at com.odobo.grails.plugin.springsecurity.rest.RestTokenValidationFilter.processFilterChain(RestTokenValidationFilter.groovy:106)
	at com.odobo.grails.plugin.springsecurity.rest.RestTokenValidationFilter.doFilter(RestTokenValidationFilter.groovy:74)
	at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.java:53)
	at at.ligaportal.ApiAuthenticationFilter.doFilter(ApiAuthenticationFilter.groovy:103)
	at com.odobo.grails.plugin.springsecurity.rest.RestAuthenticationFilter.doFilter(RestAuthenticationFilter.groovy:122)
	at grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter.doFilter(RequestHolderAuthenticationFilter.java:49)
	at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.java:82)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <g:include>: Unable to execute include: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	at C__Users_Thomas_Projekte_Ligaportal_backend_liga25_grails_app_views_gameCenter_index_gsp$_run_closure2.doCall(index.gsp:172)
	at C__Users_Thomas_Projekte_Ligaportal_backend_liga25_grails_app_views_gameCenter_index_gsp.run(index.gsp:200)
	... 13 more
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Unable to execute include: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	... 15 more
Caused by: javax.servlet.ServletException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	at grails.plugin.cache.web.filter.AbstractFilter.logThrowable(AbstractFilter.java:116)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:70)
	... 15 more
Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
	at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
	... 15 more
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [gamesOfRound] of controller [at.ligaportal.GameCenterController]  caused exception: Runtime error executing action
	... 17 more
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 17 more
Caused by: java.lang.reflect.InvocationTargetException
	... 17 more
Caused by: org.gametube.redisflexiblecache.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for RedisFlexibleDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at org.gametube.redisflexiblecache.RedisFlexibleSerializer.deserialize(RedisFlexibleSerializer.java:40)
	at org.gametube.redisflexiblecache.RedisFlexibleCacheService.doCache(RedisFlexibleCacheService.groovy:121)
	at at.ligaportal.GameCenterController$_closure1$$EPFul1QN.doCall(GameCenterController.groovy:167)
	... 17 more
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for RedisFlexibleDeserializer?; nested exception is org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at org.gametube.redisflexiblecache.RedisFlexibleSerializer.deserialize(RedisFlexibleSerializer.java:38)
	... 19 more
Caused by: org.springframework.core.NestedIOException: Failed to deserialize object type; nested exception is java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer.deserialize(RedisFlexibleDeserializer.java:49)
	... 20 more
Caused by: java.lang.ClassNotFoundException: at.ligaportal.Round_$$_javassist_103
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName(Class.java:274)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:625)
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer$1.resolveClass(RedisFlexibleDeserializer.java:40)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readClass(ObjectInputStream.java:1483)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1333)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.ArrayList.readObject(ArrayList.java:771)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at java.util.HashMap.readObject(HashMap.java:1180)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.gametube.redisflexiblecache.RedisFlexibleDeserializer.deserialize(RedisFlexibleDeserializer.java:46)
	... 20 more

Can you help me with this?

Thank you,
Thomas

**Comment by tamershahin** [comment]
Hi Thomas,

It looks like withCriteria is returning something that cannot be serialized properly. I had no time to investigate this and since I'm bit busy I will not have time for some more days. 
Please let me know if you are investigating this and if you find any clue.

Cheers,
Tamer
